INSERT INTO BASE_DIRECCION (
	RUT,
	DV,
	TIPO_DIRECCION, DIRECCION,
	CODIGO_COMUNA, CEDENTE
) SELECT
	CARGA.RUT,
	CARGA.DV,
	1 AS TIPO_DIRECCION, CARGA.DIRECCION,
	SITREL_ZONA_GEOGRAFICA.CodZona AS CODIGO_COMUNA, CARGA.CEDENTE
FROM
	CARGA
LEFT JOIN SITREL_ZONA_GEOGRAFICA ON CARGA.COMUNA = SITREL_ZONA_GEOGRAFICA.Nombre
GROUP BY
	CARGA.RUT,
	CARGA.DV,
	1,
	CARGA.DIRECCION,
	SITREL_ZONA_GEOGRAFICA.CodZona,
	CARGA.CEDENTE,
	SITREL_ZONA_GEOGRAFICA.CodNivel
HAVING
	(
		(
			(
			SITREL_ZONA_GEOGRAFICA.CodZona
			) IS NOT NULL
		)
		AND ((CARGA.CEDENTE) = "BNF")
		AND (
			(
				SITREL_ZONA_GEOGRAFICA.CodNivel
			) = "COM"
		)
	);