INSERT INTO CUADRATURA (CANTIDAD, CONCEPTO) SELECT
	Count(A.RUT_ALUMNO) AS Q_ALUMNOS,
	"RUT ALUMNO" AS Expr1
FROM
	(
		SELECT
			DEUDA.RUT_ALUMNO
		FROM
			DEUDA
		GROUP BY
			DEUDA.RUT_ALUMNO
	) AS A
GROUP BY "RUT ALUMNO";