INSERT INTO CUADRATURA (CANTIDAD, CONCEPTO) SELECT
	Count(A.NUMERO_OPERACION) AS CuentaDeNUMERO_OPERACION, "OPERACION" AS Expr1
FROM
	(
		SELECT
			DEUDA.NUMERO_OPERACION
		FROM
			DEUDA
		GROUP BY
			DEUDA.NUMERO_OPERACION
	) AS A
GROUP BY
	"OPERACION";
