INSERT INTO CUADRATURA (CANTIDAD, CONCEPTO) SELECT
	Count(A.RUT_TUTOR) AS CuentaDeRUT_TUTOR, "RUT TUTOR" AS Expr1
FROM
	(
		SELECT
			DEUDA.RUT_TUTOR
		FROM
			DEUDA
		GROUP BY
			DEUDA.RUT_TUTOR
	) AS A
GROUP BY
	"RUT TUTOR";
