SELECT
	CARGA.RUT,
	CARGA.OPERACION,
	CARGA.CUOTA,
	CARGA.VENCE,
	CARGA.MONTO
FROM
	(
		SELECT
			OP.OPERACION,
			Count(OP.RUT) AS CuentaDeRUT
		FROM
			(
				SELECT
					CARGA.RUT,
					CARGA.OPERACION,
					CARGA.TIPO_DEUDOR
				FROM
					CARGA
				GROUP BY
					CARGA.RUT,
					CARGA.OPERACION,
					CARGA.TIPO_DEUDOR
				HAVING
					(((CARGA.TIPO_DEUDOR) = "1"))
			) AS OP
		GROUP BY
			OP.OPERACION
		HAVING
			(((Count(OP.RUT)) > 1))
	) AS E01
INNER JOIN CARGA ON E01.OPERACION = CARGA.OPERACION
GROUP BY
	CARGA.RUT,
	CARGA.OPERACION,
	CARGA.CUOTA,
	CARGA.VENCE,
	CARGA.MONTO;

