INSERT INTO ASI_DIRECCIONES SELECT
	if(
	SUBSTR(	ASI_ORIGINAL_DIRECCIONES.Rut_Cliente ,1 , 1 ) < 1
,	SUBSTR(	ASI_ORIGINAL_DIRECCIONES.Rut_Cliente ,2 , 7 )
,	SUBSTR(	ASI_ORIGINAL_DIRECCIONES.Rut_Cliente ,1 , 8 )
) AS Rut_Cliente,
	RIGHT (
	ASI_ORIGINAL_DIRECCIONES.Rut_Cliente, 1
	) AS DV,
	ASI_ORIGINAL_DIRECCIONES.Tipo_Direccion,
	ASI_ORIGINAL_DIRECCIONES.Direccion,
	ASI_ORIGINAL_DIRECCIONES.Comuna,
	ASI_ORIGINAL_DIRECCIONES.Ciudad 
FROM
	ASI_ORIGINAL_DIRECCIONES;


