INSERT INTO BASE_TELEFONOS (
	RUT,
	DV,
	TELEFONO,
	ZONA,
	COMUNA,
	TIPO_TELEFONO, 
        CEDENTE,
	ORIGEN
) SELECT
	CARGA.RUT,
	CARGA.DV,
	CARGA.F7,
	SITREL_ZONA_GEOGRAFICA.CodZona AS ZONA,
	SITREL_ZONA_GEOGRAFICA.CodZona AS COMUNA,
	If (CARGA.T7= "F", 15, 16) AS Expr1,
	CARGA.CEDENTE,
	7 AS Expr2
FROM
	CARGA
INNER JOIN SITREL_ZONA_GEOGRAFICA ON CARGA.COMUNA = SITREL_ZONA_GEOGRAFICA.Nombre
GROUP BY
	CARGA.RUT,
	CARGA.DV,
	CARGA.F6,
	SITREL_ZONA_GEOGRAFICA.CodZona,
	SITREL_ZONA_GEOGRAFICA.CodZona,
	If (CARGA.T7= "F", 15, 16),
	CARGA.CEDENTE,
	7,
	SITREL_ZONA_GEOGRAFICA.CodNivel
HAVING
	(
		((CARGA.F7) IS NOT NULL)
		AND (
			(
				SITREL_ZONA_GEOGRAFICA.CodNivel
			) = "COM"
		)
	);

