UPDATE (
	(
	CARGA
	LEFT JOIN F1 ON CARGA.RUT = F1.RUT
	)
	LEFT JOIN F2 ON CARGA.RUT = F2.RUT
)
LEFT JOIN F3 ON CARGA.RUT = F3.RUT
SET CARGA.T1 = F1.TIPO, CARGA.F1 = F1.FONO, CARGA.T2 = F2.TIPO, CARGA.F2 = F2.FONO, CARGA.T3 = F3.TIPO, CARGA.F3 = F3.FONO;
