INSERT INTO BASE_TELEFONOS (
	RUT,
	DV,
	TELEFONO,
	ZONA,
	COMUNA,
	TIPO_TELEFONO , CEDENTE,
	ORIGEN
) SELECT
	CARGA.RUT,
	CARGA.DV,
	CARGA.F2,
	 SITREL_ZONA_GEOGRAFICA.CodZona AS ZONA,
	 SITREL_ZONA_GEOGRAFICA.CodZona AS COMUNA,
	If (CARGA.T2 = "F", 15, 16) AS Expr1,
	CARGA.CEDENTE,
	2 AS Expr2
FROM
	 SITREL_ZONA_GEOGRAFICA
INNER JOIN CARGA ON  SITREL_ZONA_GEOGRAFICA.CodTelArea = CARGA.CA2
GROUP BY
	CARGA.RUT,
	CARGA.DV,
	CARGA.F2,
	 SITREL_ZONA_GEOGRAFICA.CodZona,
	 SITREL_ZONA_GEOGRAFICA.CodZona,
	If (CARGA.T2 = "F", 15, 16),
	CARGA.CEDENTE,
	2,
	 SITREL_ZONA_GEOGRAFICA.CodNivel
HAVING
	(
		((CARGA.F2) IS NOT NULL)
		AND (
			(
				 SITREL_ZONA_GEOGRAFICA.CodNivel
			) = "COM"
		)
	);

