INSERT INTO BASE_TELEFONOS (
	RUT,
	DV,
	TELEFONO,
	ZONA,
	COMUNA,
	TIPO_TELEFONO , CEDENTE,
	ORIGEN
) SELECT
	CARGA.RUT,
	CARGA.DV,
	CARGA.F7,
	 SITREL_ZONA_GEOGRAFICA.CodZona AS ZONA,
	 SITREL_ZONA_GEOGRAFICA.CodZona AS COMUNA,
	If (CARGA.T7 = "F", 15, 16) AS Expr1,
	CARGA.CEDENTE,
	7 AS Expr2
FROM
	 SITREL_ZONA_GEOGRAFICA
INNER JOIN CARGA ON  SITREL_ZONA_GEOGRAFICA.CodTelArea = CARGA.CA7
where carga.f7 is not null and sitrel_zona_geografica.CodNivel like "COM"
GROUP BY
	CARGA.RUT,
	CARGA.DV,
	CARGA.F7,
	 SITREL_ZONA_GEOGRAFICA.CodZona,
	 SITREL_ZONA_GEOGRAFICA.CodZona,
	If (CARGA.T7 = "F", 15, 16),
	CARGA.CEDENTE,
	7, SITREL_ZONA_GEOGRAFICA.CodNivel